fix(navigation) - Allow injecting a doc into HvScreen
Instawork/hyperview pull request #596
Opened 2023-06-28 22:44 UTC by hgray-instawork

- Provide a document to HvScreen when it is created from HvRoute
- Use the document once in lieu of loading from url
- Remove the initial document so it won't be used after initialization completes

Asana: https://app.asana.com/0/1204008699308084/1204911836776291/f

2023-06-29 01:44 UTC, flochtililoch approved these changes

2023-06-29 02:15 UTC, flochtililoch requested changes
Looks like this is causing a regression:

https://github.com/Instawork/hyperview/assets/309515/d0387bf2-314c-4431-a05a-bb8f72d4160b

2023-06-30 17:41 UTC, hgray-instawork commented
Current resolution is to pass a clone of the document to remove the binding between HvRoute and HvScreen

2023-06-30 23:38 UTC, flochtililoch approved these changes

2023-06-30 23:53 UTC, merged